apiVersion: apps/v1
kind: Deployment
metadata:
  name: dist-lock-app
  labels:
    app: dist-lock-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dist-lock-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: dist-lock-app
    spec:
      containers:
        - name: dist-lock-app
          image: dist-lock-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          envFrom:
            - configMapRef:
                name: dist-lock-app-config
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: ZK_CONNECTION_STRING
              value: zookeeper-headless:2181