apiVersion: v1
kind: Service
metadata:
  name: dist-lock-app
  labels:
    app: dist-lock-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: dist-lock-app
  type: ClusterIP